{
 "title": "Containers",
 "description": "Docker stats on all containers, including Supervisor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(container_device_short_uuid)"
    }
   },
   { "name": "container", "label": "Container", "query": { "query": "label_values(container_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization by Containers",
   "type": "gauge",
   "description": "Cumulative cpu time consumed in seconds.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_percent{container_device_short_uuid=~\"$instance\", container_name=~\"$container\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Memory Utilization by Containers",
   "type": "gauge",
   "description": "Current memory usage in bytes, including all memory regardless of when it was accessed.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_total{container_device_short_uuid=~\"$instance\", container_name=~\"$container\"}) / avg(node_memory_MemTotal_bytes{instance =~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Reserved by Containers",
   "type": "gauge",
   "description": "Memory reserved by the containers on the machine.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_limit{container_device_short_uuid=~\"$instance\", container_name=~\"$container\"}) / avg(node_memory_MemTotal_bytes{ instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Compute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Cpu time consumed in seconds by container.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (container_name) (rate(container_cpu_percent{container_device_short_uuid =~\"$instance\", container_name=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Current memory usage in bytes, including all memory regardless of when it was accessed by container.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container_name) (container_memory_usage_total{container_device_short_uuid=~\"$instance\", container_name=~\"$container\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}